load("@rules_go//go:def.bzl", "go_library")
load("//tools:go.bzl", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "crypto.c",
        "crypto.go",
        "crypto.h",
        "crypto_amd64.go",
        "crypto_slow.go",
    ],
    cgo = True,
    copts = select({
        "@rules_go//go/platform:amd64": [
            "-march=native",
        ],
        "//conditions:default": [],
    }),
    importpath = "github.com/scionproto/scion/pkg/fcrypto",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:amd64": [
            "@org_golang_x_sys//cpu:go_default_library",
        ],
        "//conditions:default": [],
    }),
)

go_test(
    name = "go_default_test",
    srcs = [
        "crypto_test.go",
        "export_test.go",
    ],
    embed = [":go_default_library"],
    deps = select({
        "@rules_go//go/platform:amd64": [
            "@com_github_stretchr_testify//assert:go_default_library",
        ],
        "//conditions:default": [],
    }),
)
